management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always

spring:
    boot:
        admin:
            client:
                url: http://localhost:8082

Logging:
    file:
        name: company-service.log
        max-history: 20
        max-size: 20MB